import { Candidate, CandidateStage, CandidateSource } from '@/types/candidate'
import { Job } from '@/types/job'
import { Automation, OutreachMessage } from '@/types/automation'

// Mock Candidates
export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'c1',
    name: 'Alex Rivera',
    email: 'alex.rivera@email.com',
    avatar: '',
    title: 'Senior Frontend Engineer',
    company: 'Meta',
    location: 'San Francisco, CA',
    skills: ['React', 'TypeScript', 'GraphQL', 'Next.js', 'TailwindCSS'],
    experience: 6,
    matchScore: 94,
    stage: 'interview',
    source: 'linkedin',
    jobId: 'j1',
    jobTitle: 'Lead Frontend Engineer',
    tags: ['Top Match', 'FAANG'],
    createdAt: '2024-11-15T10:00:00Z',
    updatedAt: '2024-12-01T14:30:00Z',
  },
  {
    id: 'c2',
    name: 'Priya Sharma',
    email: 'priya.sharma@email.com',
    avatar: '',
    title: 'Full Stack Developer',
    company: 'Stripe',
    location: 'New York, NY',
    skills: ['Node.js', 'React', 'PostgreSQL', 'AWS', 'Python'],
    experience: 4,
    matchScore: 87,
    stage: 'screening',
    source: 'github',
    jobId: 'j2',
    jobTitle: 'Backend Engineer',
    tags: ['Strong Profile'],
    createdAt: '2024-11-18T09:00:00Z',
    updatedAt: '2024-11-28T11:00:00Z',
  },
  {
    id: 'c3',
    name: 'Marcus Johnson',
    email: 'marcus.j@email.com',
    avatar: '',
    title: 'Machine Learning Engineer',
    company: 'OpenAI',
    location: 'Remote',
    skills: ['Python', 'PyTorch', 'LLMs', 'MLOps', 'Kubernetes'],
    experience: 5,
    matchScore: 91,
    stage: 'offer',
    source: 'referral',
    jobId: 'j3',
    jobTitle: 'ML Engineer',
    tags: ['Top Match', 'AI Expert'],
    createdAt: '2024-11-10T08:00:00Z',
    updatedAt: '2024-12-02T16:00:00Z',
  },
  {
    id: 'c4',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@email.com',
    avatar: '',
    title: 'Product Designer',
    company: 'Figma',
    location: 'Seattle, WA',
    skills: ['Figma', 'Design Systems', 'Prototyping', 'User Research'],
    experience: 3,
    matchScore: 78,
    stage: 'sourced',
    source: 'linkedin',
    jobId: 'j4',
    jobTitle: 'Senior Product Designer',
    tags: ['Creative'],
    createdAt: '2024-12-01T12:00:00Z',
    updatedAt: '2024-12-01T12:00:00Z',
  },
  {
    id: 'c5',
    name: 'Daniel Kim',
    email: 'daniel.kim@email.com',
    avatar: '',
    title: 'DevOps Engineer',
    company: 'Netflix',
    location: 'Los Angeles, CA',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Docker'],
    experience: 7,
    matchScore: 89,
    stage: 'interview',
    source: 'website',
    jobId: 'j5',
    jobTitle: 'Senior DevOps Engineer',
    tags: ['Infrastructure Expert'],
    createdAt: '2024-11-20T14:00:00Z',
    updatedAt: '2024-12-02T10:00:00Z',
  },
  {
    id: 'c6',
    name: 'Sofia Chen',
    email: 'sofia.chen@email.com',
    avatar: '',
    title: 'Data Scientist',
    company: 'Airbnb',
    location: 'Remote',
    skills: ['Python', 'SQL', 'Machine Learning', 'Spark', 'Tableau'],
    experience: 4,
    matchScore: 72,
    stage: 'screening',
    source: 'linkedin',
    jobId: 'j6',
    jobTitle: 'Data Scientist',
    tags: [],
    createdAt: '2024-11-25T09:30:00Z',
    updatedAt: '2024-11-29T15:00:00Z',
  },
  {
    id: 'c7',
    name: 'James O\'Brien',
    email: 'james.obrien@email.com',
    avatar: '',
    title: 'Engineering Manager',
    company: 'Spotify',
    location: 'Austin, TX',
    skills: ['Leadership', 'Agile', 'System Design', 'React', 'Node.js'],
    experience: 10,
    matchScore: 85,
    stage: 'hired',
    source: 'referral',
    jobId: 'j1',
    jobTitle: 'Engineering Manager',
    tags: ['Leadership'],
    createdAt: '2024-10-15T10:00:00Z',
    updatedAt: '2024-11-20T12:00:00Z',
  },
  {
    id: 'c8',
    name: 'Aisha Patel',
    email: 'aisha.patel@email.com',
    avatar: '',
    title: 'Backend Engineer',
    company: 'Uber',
    location: 'Chicago, IL',
    skills: ['Go', 'Microservices', 'gRPC', 'PostgreSQL', 'Redis'],
    experience: 5,
    matchScore: 82,
    stage: 'sourced',
    source: 'github',
    jobId: 'j2',
    jobTitle: 'Backend Engineer',
    tags: [],
    createdAt: '2024-12-02T08:00:00Z',
    updatedAt: '2024-12-02T08:00:00Z',
  },
]

// Mock Jobs
export const MOCK_JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Lead Frontend Engineer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    type: 'full-time',
    status: 'active',
    candidateCount: 34,
    interviewCount: 8,
    hiresCount: 1,
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
    hiringManager: 'Sarah Mitchell',
    remote: true,
    salaryMin: 160000,
    salaryMax: 220000,
  },
  {
    id: 'j2',
    title: 'Backend Engineer',
    department: 'Engineering',
    location: 'New York, NY',
    type: 'full-time',
    status: 'active',
    candidateCount: 28,
    interviewCount: 6,
    hiresCount: 0,
    createdAt: '2024-10-15T00:00:00Z',
    updatedAt: '2024-11-30T00:00:00Z',
    hiringManager: 'Tom Walker',
    remote: false,
    salaryMin: 140000,
    salaryMax: 190000,
  },
  {
    id: 'j3',
    title: 'ML Engineer',
    department: 'AI/ML',
    location: 'Remote',
    type: 'full-time',
    status: 'active',
    candidateCount: 19,
    interviewCount: 4,
    hiresCount: 0,
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-12-02T00:00:00Z',
    hiringManager: 'Lisa Park',
    remote: true,
    salaryMin: 180000,
    salaryMax: 250000,
  },
  {
    id: 'j4',
    title: 'Senior Product Designer',
    department: 'Design',
    location: 'Seattle, WA',
    type: 'full-time',
    status: 'active',
    candidateCount: 15,
    interviewCount: 3,
    hiresCount: 0,
    createdAt: '2024-11-10T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
    hiringManager: 'Rachel Green',
    remote: true,
    salaryMin: 130000,
    salaryMax: 170000,
  },
  {
    id: 'j5',
    title: 'Senior DevOps Engineer',
    department: 'Infrastructure',
    location: 'Austin, TX',
    type: 'full-time',
    status: 'active',
    candidateCount: 12,
    interviewCount: 2,
    hiresCount: 0,
    createdAt: '2024-11-15T00:00:00Z',
    updatedAt: '2024-12-02T00:00:00Z',
    hiringManager: 'Kevin Zhang',
    remote: false,
    salaryMin: 150000,
    salaryMax: 200000,
  },
  {
    id: 'j6',
    title: 'Data Scientist',
    department: 'Analytics',
    location: 'Remote',
    type: 'full-time',
    status: 'paused',
    candidateCount: 22,
    interviewCount: 5,
    hiresCount: 0,
    createdAt: '2024-09-20T00:00:00Z',
    updatedAt: '2024-11-25T00:00:00Z',
    hiringManager: 'Anna White',
    remote: true,
    salaryMin: 120000,
    salaryMax: 160000,
  },
]

// Mock Automations
export const MOCK_AUTOMATIONS: Automation[] = [
  {
    id: 'a1',
    name: 'High-Match Outreach',
    description: 'Auto-send personalized emails to candidates with match score > 80',
    status: 'active',
    nodes: [],
    edges: [],
    triggerCount: 147,
    lastTriggered: '2024-12-02T14:30:00Z',
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2024-12-02T14:30:00Z',
  },
  {
    id: 'a2',
    name: 'Interview Reminder Sequence',
    description: 'Send reminders to candidates 24h and 1h before scheduled interviews',
    status: 'active',
    nodes: [],
    edges: [],
    triggerCount: 89,
    lastTriggered: '2024-12-02T09:00:00Z',
    createdAt: '2024-10-15T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 'a3',
    name: 'Rejection Notification',
    description: 'Auto-send professional rejection emails after pipeline stage update',
    status: 'active',
    nodes: [],
    edges: [],
    triggerCount: 213,
    lastTriggered: '2024-12-01T18:00:00Z',
    createdAt: '2024-09-01T00:00:00Z',
    updatedAt: '2024-11-30T00:00:00Z',
  },
  {
    id: 'a4',
    name: 'LinkedIn Sourcing Bot',
    description: 'Automatically source and score candidates from LinkedIn searches',
    status: 'paused',
    nodes: [],
    edges: [],
    triggerCount: 56,
    lastTriggered: '2024-11-20T12:00:00Z',
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-11-20T12:00:00Z',
  },
]

// Mock Outreach Messages
export const MOCK_OUTREACH: OutreachMessage[] = [
  {
    id: 'o1',
    candidateId: 'c1',
    candidateName: 'Alex Rivera',
    candidateEmail: 'alex.rivera@email.com',
    subject: 'Exciting opportunity at AutoHyre - Lead Frontend Engineer',
    status: 'replied',
    sentAt: '2024-11-16T10:00:00Z',
    openedAt: '2024-11-16T11:30:00Z',
    repliedAt: '2024-11-16T14:00:00Z',
  },
  {
    id: 'o2',
    candidateId: 'c2',
    candidateName: 'Priya Sharma',
    candidateEmail: 'priya.sharma@email.com',
    subject: 'Backend Engineer role that matches your profile',
    status: 'opened',
    sentAt: '2024-11-19T09:00:00Z',
    openedAt: '2024-11-19T12:00:00Z',
  },
  {
    id: 'o3',
    candidateId: 'c4',
    candidateName: 'Yuki Tanaka',
    candidateEmail: 'yuki.tanaka@email.com',
    subject: 'Senior Product Designer - would love to connect',
    status: 'sent',
    sentAt: '2024-12-01T14:00:00Z',
  },
  {
    id: 'o4',
    candidateId: 'c8',
    candidateName: 'Aisha Patel',
    candidateEmail: 'aisha.patel@email.com',
    subject: 'Backend Engineer opportunity - perfect match',
    status: 'scheduled',
    scheduledAt: '2024-12-03T09:00:00Z',
  },
]

export const STAGE_COLORS: Record<string, string> = {
  sourced:   'bg-neutral-100 text-neutral-600 border-neutral-200',
  screening: 'bg-info-50 text-info-700 border-info-200',
  interview: 'bg-primary-50 text-primary-600 border-primary-100',
  offer:     'bg-warning-50 text-warning-700 border-warning-200',
  hired:     'bg-success-50 text-success-700 border-success-200',
  rejected:  'bg-error-50 text-error-700 border-error-200',
}

export const STATUS_COLORS: Record<string, string> = {
  active:  'bg-success-50 text-success-700 border-success-200',
  paused:  'bg-warning-50 text-warning-700 border-warning-200',
  closed:  'bg-neutral-100 text-neutral-600 border-neutral-200',
  draft:   'bg-info-50 text-info-700 border-info-200',
  error:   'bg-error-50 text-error-700 border-error-200',
}

export const NAV_ITEMS = [
  { href: '/dashboard', label: 'Dashboard', icon: 'LayoutDashboard' },
  { href: '/jobs', label: 'Jobs', icon: 'Briefcase' },
  { href: '/candidates', label: 'Candidates', icon: 'Users' },
  { href: '/pipeline', label: 'Pipeline', icon: 'Kanban' },
  { href: '/automations', label: 'Automations', icon: 'Zap' },
  { href: '/outreach', label: 'Outreach', icon: 'Mail' },
  { href: '/analytics', label: 'Analytics', icon: 'BarChart3' },
  { href: '/integrations', label: 'Integrations', icon: 'Puzzle' },
  { href: '/settings', label: 'Settings', icon: 'Settings' },
]
